spring:
  application:
    name: zyberhero

  datasource:
    url: jdbc:postgresql://localhost:5432/zyberhero
    username: appuser                                                   
    password: apppassword123                                                    
    driver-class-name: org.postgresql.Driver                           
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect   
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ikoncloud-dev.keross.com/ikon-api/platform

logging:
  level:
    com.ikon: DEBUG
  file:
    name: "../logs/${spring.application.name}-app.log"

server:
  port: 8060
